# Matrices
## Exercise 1 - Basic operations
Given the following matrices:
``` python
A = [[1, 2],
     [3, 4]]
B = [[5, 6],
     [7, 8]]
c = 3
```
Make the following operations:
1. A + B
2. c * A
3. A^T
4. is A + B = B + A? Why?, explain

In [55]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
c = 3

In [56]:
SUM = A + B
print(SUM)

[[ 6  8]
 [10 12]]


In [57]:
SCALAR = c * A
print(SCALAR)

[[ 3  6]
 [ 9 12]]


In [58]:
AT = A.T
print(AT)

[[1 3]
 [2 4]]


In [59]:
SUMAB = A + B
SUMBA = B + A
print(SUMAB == SUMBA) # So yes, the sum is commutative

[[ True  True]
 [ True  True]]


## Exercise 2 - Matrix multiplication
Given the following matrices:
``` python
A = [[1, 2, 3],
     [4, 5, 6]]
B = [[1, 0],
     [0, 1],
     [1, 0]]
```
1. Calculate A @ B
2. is it possible to calculate B @ A? If it is, what is its shape?
3. Create matrix identity of the right size and verify A @ I = A

In [60]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 0], [0, 1], [1, 0]])

In [61]:
PROD_AB = A @ B
print(PROD_AB)

[[ 4  2]
 [10  5]]


In [62]:
PROD_BA = B @ A
print(PROD_BA)

[[1 2 3]
 [4 5 6]
 [1 2 3]]


In [63]:
print(f"A @ B shape: {PROD_AB.shape}")  # (2, 2)
print(f"B @ A shape: {PROD_BA.shape}")  # (3, 3)
# Conclusion: A@B != B@A — the matrices multiplication is not commutative

A @ B shape: (2, 2)
B @ A shape: (3, 3)


In [64]:
# A shape (2x3), so identity has to be (3x3) for this valid result A @ I
# The rule: A (m x n) @ I (n x n) = A (m x n)
A_IDENTITY = np.eye(3)
NEW_A = A @ A_IDENTITY
print(NEW_A == A)

[[ True  True  True]
 [ True  True  True]]
