# Matrices
## Exercise 1 - Basic operations
Given the following matrices:
``` python
A = [[1, 2],
     [3, 4]]
B = [[5, 6],
     [7, 8]]
c = 3
```
Make the following operations:
1. A + B
2. c * A
3. A^T
4. is A + B = B + A? Why?, explain

In [81]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
c = 3

In [82]:
SUM = A + B
print(SUM)

[[ 6  8]
 [10 12]]


In [83]:
SCALAR = c * A
print(SCALAR)

[[ 3  6]
 [ 9 12]]


In [84]:
AT = A.T
print(AT)

[[1 3]
 [2 4]]


In [85]:
SUMAB = A + B
SUMBA = B + A
print(SUMAB == SUMBA) # So yes, the sum is commutative

[[ True  True]
 [ True  True]]


## Exercise 2 - Matrix multiplication
Given the following matrices:
``` python
A = [[1, 2, 3],
     [4, 5, 6]]
B = [[1, 0],
     [0, 1],
     [1, 0]]
```
1. Calculate A @ B
2. is it possible to calculate B @ A? If it is, what is its shape?
3. Create matrix identity of the right size and verify A @ I = A

In [86]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 0], [0, 1], [1, 0]])

In [87]:
PROD_AB = A @ B
print(PROD_AB)

[[ 4  2]
 [10  5]]


In [88]:
PROD_BA = B @ A
print(PROD_BA)

[[1 2 3]
 [4 5 6]
 [1 2 3]]


In [89]:
print(f"A @ B shape: {PROD_AB.shape}")  # (2, 2)
print(f"B @ A shape: {PROD_BA.shape}")  # (3, 3)
# Conclusion: A@B != B@A — the matrices multiplication is not commutative

A @ B shape: (2, 2)
B @ A shape: (3, 3)


In [90]:
# A shape (2x3), so identity has to be (3x3) for this valid result A @ I
# The rule: A (m x n) @ I (n x n) = A (m x n)
A_IDENTITY = np.eye(3)
NEW_A = A @ A_IDENTITY
print(NEW_A == A)

[[ True  True  True]
 [ True  True  True]]


## Exercise 3: Transposed
Given the following matrix calculate:
``` python
A = [[1, 2, 3],
     [4, 5, 6]]
```
1. Transposed manually
2. Verify ```(A^T)^T = A``` with Numpy
3. Create a symmetric matrix 3x3 abd verify that ```S = S^T```
4. Given ```v = [1, 2, 3]``` calculate ```v^T @ v``` and ```v @ v^T``` with Numpy, what are the resulting shapes?, Did you recognize anyone?

In [91]:
## 2) Verify (A^T)^T = A
A = np.array([[1, 2, 3], [4, 5, 6]])
print(np.allclose(A.T.T, A))

True


In [92]:
## 3) Symmetric matrix
S = np.array([[4, 1, 5], [1, 6, 3], [5, 3, 9]])
print(np.allclose(S, S.T))

True


In [93]:
## 4) v^T @ v vs v @ v^T
v = np.array([1, 2, 3])

# v @ v -> scalar 14  (shape: ())
# This is the v point product from itself = ||v||^2 = 1^2 + 2^2 + 3^2 = 14
print(v @ v)
print(f"shape: {(v @ v).shape}")

# v @ v^T -> matrix 3x3  (exterior product)
# Every element [i,j] = v[i] * v[j]
# This matrix appears in ML, in the sizes update (gradient outer product)
print(np.outer(v, v))
print(f"shape: {np.outer(v, v).shape}")

14
shape: ()
[[1 2 3]
 [2 4 6]
 [3 6 9]]
shape: (3, 3)


## Exercise 4: Inverse and determinant
Given the following equation system:
```
Eq1: 2x + y = 5
Eq2: 5x + 3y = 13
```
Calculate:
1. Write the system in its matrix form Ax = b
2. Calculate the ```det(A)``` manually
3. Solve with ```np.linalg.solve(A, b)```
4. Verify ```A @ x``` is ```b```

In [94]:
## System definition
A = np.array([[2, 1], [5, 3]])
b = np.array([5, 13])

In [95]:
## 2) Determinant calculation
det_A = np.linalg.det(A)
print(f"det(A) = {det_A}")
print("Has inverse and unique solution" if det_A != 0 else "No unique solution")

det(A) = 1.0000000000000002
Has inverse and unique solution


In [96]:
## 3) Calculate np.linalg.solve
solution = np.linalg.solve(A, b)
print(solution)

[2. 1.]


In [97]:
## Verification
print(np.allclose(b, A @ solution))

True
