# Matrices
## Exercise 1 - Basic operations
Given the following matrices:
``` python
A = [[1, 2],
     [3, 4]]
B = [[5, 6],
     [7, 8]]
c = 3
```
Make the following operations:
1. A + B
2. c * A
3. A^T
4. is A + B = B + A? Why?, explain

In [10]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
c = 3

In [11]:
SUM = A + B
print(SUM)

[[ 6  8]
 [10 12]]


In [12]:
SCALAR = c * A
print(SCALAR)

[[ 3  6]
 [ 9 12]]


In [13]:
AT = A.T
print(AT)

[[1 3]
 [2 4]]


In [14]:
SUMAB = A + B
SUMBA = B + A
print(SUMAB == SUMBA) # So yes, the sum is commutative

[[ True  True]
 [ True  True]]
