# Vectors
## Exercise 1 - Basic operations
Given the following information:
``` python
a = [2, -1, 4]
b = [3,  2, -1]
c = -2
```
Make the following operations:
1. a + b
2. c * a
3. a - b
4. a · b

In [1]:
import numpy as np

# Information
a = np.array([2, -1, 4])
b = np.array([3, 2, -1])
c = -2

In [2]:
vector_one = a + b
print(vector_one.__str__())

[5 1 3]


In [3]:
vector_two = c * a
print(vector_two.__str__())

[-4  2 -8]


In [4]:
vector_three = a - b
print(vector_three.__str__())

[-1 -3  5]


In [5]:
dot = np.dot(a, b)
print(dot)

0
