# Vectors
## Exercise 1 - Basic operations
Given the following information:
``` python
a = [2, -1, 4]
b = [3,  2, -1]
c = -2
```
Make the following operations:
1. a + b
2. c * a
3. a - b
4. a · b

In [29]:
import numpy as np

# Information
a = np.array([2, -1, 4])
b = np.array([3, 2, -1])
c = -2

In [30]:
vector_one = a + b
print(vector_one.__str__())

[5 1 3]


In [31]:
vector_two = c * a
print(vector_two.__str__())

[-4  2 -8]


In [32]:
vector_three = a - b
print(vector_three.__str__())

[-1 -3  5]


In [33]:
dot = np.dot(a, b)
print(dot)

0


## Exercise 2 - Norm L2
Given the following vector `v = [1, 2, 2]` let's calculate the following operations:
1. Calculate ‖v‖₂
2. Calculate the unit vector v̂ = v / ‖v‖
3. Verify ‖v̂‖ = 1.0 — why?

In [34]:
v = np.array([1, 2, 2])

In [35]:
norm_l2 = np.linalg.norm(v)
print(norm_l2)

3.0


In [36]:
unit_v = v / norm_l2
print(unit_v)
print(np.linalg.norm(unit_v))

[0.33333333 0.66666667 0.66666667]
0.9999999999999999
