# Vectors
## Exercise 1 - Basic operations
Given the following information:
``` python
a = [2, -1, 4]
b = [3,  2, -1]
c = -2
```
Make the following operations:
1. a + b
2. c * a
3. a - b
4. a · b

In [106]:
import math

import numpy as np

# Information
a = np.array([2, -1, 4])
b = np.array([3, 2, -1])
c = -2

In [107]:
vector_one = a + b
print(vector_one.__str__())

[5 1 3]


In [108]:
vector_two = c * a
print(vector_two.__str__())

[-4  2 -8]


In [109]:
vector_three = a - b
print(vector_three.__str__())

[-1 -3  5]


In [110]:
dot = np.dot(a, b)
print(dot)

0


## Exercise 2 - Norm L2
Given the following vector `v = [1, 2, 2]` let's calculate the following operations:
1. Calculate ‖v‖₂
2. Calculate the unit vector v̂ = v / ‖v‖
3. Verify ‖v̂‖ = 1.0 — why?

In [111]:
v = np.array([1, 2, 2])

In [112]:
norm_l2 = np.linalg.norm(v)
print(norm_l2)

3.0


In [113]:
unit_v = v / norm_l2
print(unit_v)
print(np.linalg.norm(unit_v))

[0.33333333 0.66666667 0.66666667]
1.0


## Exercise 3 - Norm identity/Dot product
Given the following vector `v = [3, -4, 0, 1]` let's calculate the following operations:
1. Calculate v · v
2. Calculate ‖v‖²

In [114]:
v = np.array([3, -4, 0, 1])

In [115]:
new_dot_product = v @ v
print(new_dot_product)

26


In [116]:
dot_product = np.linalg.norm(v) ** 2
print(dot_product)

25.999999999999996


## Exercise 4 - Orthogonality
With the following vector we are going to calculate the orthogonality between them:
- u = [1, 2, 3]
- v = [-3, 0, 1]
- w = [2, -5, 4]

So, calculate the following operations `u·v`, `u·w` and `v·w` and determine which of them are orthogonal

In [117]:
u = np.array([1, 2, 3])
v = np.array([-3, 0, 1])
w = np.array([2, -5, 4])

In [118]:
u_v = u @ v
print(u_v) # 0 -> this are orthogonal

0


In [119]:
u_w = u @ w
print(u_w) # > 0 acute angle

4


In [120]:
v_w = v @ w
print(v_w) # < 0 obtuse angle

-2


In [121]:
angle = math.degrees(math.acos(u_v / np.linalg.norm(u) * np.linalg.norm(v)))
print(angle)

90.0
